In [1]:
from six.moves import urllib
opener = urllib.request.build_opener()
opener.addheaders = [('User-agent', 'Mozilla/5.0')]
urllib.request.install_opener(opener)

In [3]:
import torch
from torch import nn
import torch.nn.functional as F
from torchvision import datasets, transforms

transform = transforms.Compose([transforms.ToTensor(),
                                 transforms.Normalize((0.5,),(0.5,)),
                                 ])

trainset = datasets.MNIST('~/.pytorch/MNIST_data/', download = True, train = True, transform = transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size = 64, shuffle = True)


Extracting /root/.pytorch/MNIST_data/MNIST/raw/train-images-idx3-ubyte.gz to /root/.pytorch/MNIST_data/MNIST/raw




Extracting /root/.pytorch/MNIST_data/MNIST/raw/train-labels-idx1-ubyte.gz to /root/.pytorch/MNIST_data/MNIST/raw




Extracting /root/.pytorch/MNIST_data/MNIST/raw/t10k-images-idx3-ubyte.gz to /root/.pytorch/MNIST_data/MNIST/raw




Extracting /root/.pytorch/MNIST_data/MNIST/raw/t10k-labels-idx1-ubyte.gz to /root/.pytorch/MNIST_data/MNIST/raw



/usr/local/lib/python3.7/dist-packages/torchvision/datasets/mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


In [5]:
model = nn.Sequential(nn.Linear(784,128),
                      nn.ReLU(),
                      nn.Linear(128,64),
                      nn.ReLU(),
                      nn.Linear(64,10))
#define the loss
criterion = nn.CrossEntropyLoss()

#Get the data
dataiter = iter(trainloader)

images, labels = next(dataiter)

#Flatten the image
images = images.view(images.shape[0], -1)

logits = model(images)
loss = criterion(logits,labels)
print(loss)


tensor(2.3294, grad_fn=<NllLossBackward>)


In [6]:
model = nn.Sequential(nn.Linear(784,128),
                      nn.ReLU(),
                      nn.Linear(128,64),
                       nn.ReLU(),
                      nn.Linear(64,10),
                      nn.LogSoftmax(dim = 1))

criterion = nn.NLLLoss()

dataiter = iter(trainloader)
images,labels= next(dataiter)
images = images.view(images.shape[0],-1)
logits = model(images)
loss = criterion(logits,labels)
print(loss)


tensor(2.2881, grad_fn=<NllLossBackward>)


In [7]:
x = torch.randn(2,2, requires_grad =True)
print(x)

tensor([[ 1.2546, -0.1293],
        [ 2.0894,  1.4822]], requires_grad=True)


In [8]:
y = x**2
print(y)

tensor([[1.5740, 0.0167],
        [4.3658, 2.1969]], grad_fn=<PowBackward0>)


In [9]:
print(y.grad_fn)

In [10]:
z = y.mean()

In [12]:
print(x.grad)

None


In [13]:
z.backward()

In [14]:
print(x.grad
      )

tensor([[ 0.6273, -0.0647],
        [ 1.0447,  0.7411]])


In [15]:
print(x/2
      )

tensor([[ 0.6273, -0.0647],
        [ 1.0447,  0.7411]], grad_fn=<DivBackward0>)


In [16]:
print(model[0].weight.grad)

None


In [17]:
loss.backward()
print(model[0].weight.grad)

tensor([[ 0.0017,  0.0017,  0.0017,  ...,  0.0017,  0.0017,  0.0017],
        [-0.0031, -0.0031, -0.0031,  ..., -0.0031, -0.0031, -0.0031],
        [ 0.0009,  0.0009,  0.0009,  ...,  0.0009,  0.0009,  0.0009],
        ...,
        [-0.0009, -0.0009, -0.0009,  ..., -0.0009, -0.0009, -0.0009],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-0.0036, -0.0036, -0.0036,  ..., -0.0036, -0.0036, -0.0036]])


In [18]:
from torch import optim
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [21]:
model = nn.Sequential(nn.Linear(784, 128),
                      nn.ReLU(),
                      nn.Linear(128, 64),
                      nn.ReLU(),
                      nn.Linear(64, 10),
                      nn.LogSoftmax(dim=1))
criterion = nn.NLLLoss()
optimizer = optim.SGD(model.parameters(),lr =0.003)
epochs = 5
for e in range(epochs):
  running_loss =0
  for images, labels in trainloader:
    images = images.view(images.shape[0],-1)
    output = model(images)
    loss = criterion(output,labels)
    running_loss += loss.item()
  else:
    print(f"Training loss: {running_loss/len(trainloader)}")

Training loss: 2.315209158448014
Training loss: 2.315220178063236
Training loss: 2.3152086798316125
Training loss: 2.3152139575750845
Training loss: 2.3152206223656626


In [22]:
loss.item()

2.311758279800415

In [23]:
len(trainloader
    )

938

In [24]:
running_loss

2171.6769437789917

In [ ]:
'''''jalebi baby'''''